### PR TITLE
Add support for reading properties

### PR DESCRIPTION
**Pull request by njoysubho**
@creekorful thanks for this utility. I needed support for reading properties in a pom.xml, so I thought of creating this PR .

### CODE REVIEW

**Comment by creekorful** [comment]
Hello @njoysubho,
Thanks for the PR (and the tests :D) !

I only have a little suggestion:
Why not simply define **Properties** like this:

```golang
type Properties map[string]string
```

Since we only have key value for properties it will ease later usage:

```golang
project.Properties["project.build.sourceEncoding"]
```

Instead of

```golang
project.Properties.PropertyMap["project.build.sourceEncoding"]
```

What do you think?

**Comment by njoysubho** [comment]
@creekorful  Yes, I agree that's a good idea. I made the change. I must admit I am a newbie in Golang world so I hope new changes adhere to Golang way of doing things

**Review by creekorful — APPROVED** [review]

**Comment by creekorful** [comment]
Everything looks good to me!

Thanks for the PR 👍🏻

**Comment by creekorful** [comment]
Changes has been released as 1.4.0.

Thanks again :D

**Pull request merged**
